I can bookmark a racipe
syboulette/fridgi pull request #76
Opened 2023-03-20 19:18 UTC by Za-hell

2023-03-20 20:00 UTC, akramerin commented on app/models/user.rb
> +  has_many :recipes, through: :favorite_recipes
i am not sure about that - should it not be: has_many :recipes (as in the ones that he created) additionally to the current line nine?

also: still the old (better :D ) spelling

2023-03-20 20:00 UTC, akramerin commented on app/views/favourite_recipes/index.html.erb
> +    <%= link_to "#{p.name}", favorite_recipes(p)%>
spelling

2023-03-21 09:56 UTC, syboulette requested changes

2023-03-21 09:56 UTC, syboulette commented on app/views/recipes/index.html.erb
@Za-hell can we use the term favourite please? I feel like book mark is not super nice, also we always talked about favorites. Please stick to what we agreed on at the begining ;)

2023-03-21 09:56 UTC, syboulette commented on app/views/recipes/index.html.erb
> +    <%= f.submit "Bookmark", class: "btn btn-danger pic-large", id: "buttonz" %>
Can we have a little heart that fills up when marked as favourite like we have on the figma? 🙏

2023-03-21 09:56 UTC, syboulette commented on app/views/recipes/index.html.erb
> +    <%= f.submit "Bookmark", class: "btn btn-danger pic-large", id: "buttonz" %>
a big button on the card will not work

2023-03-21 09:56 UTC, syboulette commented on db/schema.rb
> +  create_table "favorites", force: :cascade do |t|
@Za-hell can we keep the "favorite" spelling across the code as it is the one you decided on for the schema? thanks!

2023-03-21 09:56 UTC, syboulette commented on app/controllers/favourite_recipes_controller.rb
> +  before_action :authenticate_user!, only: :create
@Za-hell keep it consistant with the schema, please use "Favorite"

2023-03-21 09:56 UTC, syboulette commented on app/controllers/favourite_recipes_controller.rb
> +    @favourite_recipe = FavouriteRecipe.new(favourite_recipe_params)
@Za-hell Favorite

2023-03-21 09:56 UTC, syboulette commented on app/controllers/recipes_controller.rb
> +    @favourite_recipe = FavouriteRecipe.new
@Za-hell Favorite

2023-03-21 09:56 UTC, syboulette commented on app/views/favourite_recipes/index.html.erb
> +  <%= current_user.favourite_recipes.each do |p| %>
@Za-hell Favorite

2023-03-21 09:56 UTC, syboulette commented on app/views/recipes/index.html.erb
> +<%= simple_form_for @favourite_recipe do |f| %>
@Za-hell Favorite

2023-03-21 09:56 UTC, syboulette commented on config/routes.rb
> +  resources :favourite_recipes, only: [:new, :create, :edit, :index]
@Za-hell Favorite

2023-03-21 09:56 UTC, syboulette commented on test/controllers/favorite_recipes_controller_test.rb
> +  # test "the truth" do
@Za-hell You created routes for new, create, index,edit and update. I think we also need a destroy as people might not want the recipe in their favourites anymore.
Also need the actions in here. Thanks!
S

2023-03-21 15:25 UTC, closed without merging