Edit account
syboulette/fridgi pull request #85
Opened 2023-03-27 18:25 UTC by D-Zaleski

just added the required fields to edit account
delete function works
need to setup cloudinary for avatar

2023-03-27 19:26 UTC, syboulette requested changes

2023-03-27 19:26 UTC, syboulette commented on config/application.rb
> -
Any reason why you deleted the configuration of the entire app?

2023-03-27 19:35 UTC, syboulette approved these changes

2023-03-28 07:38 UTC, akramerin reviewed
lgtm - except for the log/tmp -files. please remove!

2023-03-28 17:52 UTC, syboulette commented
@D-Zaleski you still have a lot of bin files and the log devellopment

2023-03-28 18:38 UTC, syboulette commented
@D-Zaleski Still a lot of cache

2023-03-28 19:03 UTC, syboulette approved these changes

2023-03-28 19:04 UTC, merged